### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Bladadah** [xbread/Open-Source-Santos#1]
Hello, I need some help with installing and I also need the modpack for the server

**Comment by xbread** [comment]
Install the file into your gamemodes folder 

Setup 
* Configure sv_config.lua 
* Add these to your content pack: [here](https://steamcommunity.com/workshop/filedetails/?id=666613700)
* Note you will need a MySQL Database and tmysql4 installed

**Comment by Bladadah** [comment]
Ah ok, set it up and it's giving a lot of errors lol. 
https://pastebin.com/97mmR04z

**Comment by xbread** [comment]
Make sure you have 
* tmysql 
* your sql has external connections
* you're using one of the maps listed in santosrp/maps

**Comment by Bladadah** [comment]
Yuh got all that I figured out the problem, i'm in the server and now I have this error in this server when I am in it.

[ERROR] gamemodes/santosrp/gamemode/sh_pacmodels.lua:92: attempt to index global 'pac' (a nil value)
  1. InvalidatePlayerOutfits - gamemodes/santosrp/gamemode/sh_pacmodels.lua:92
   2. UpdatePlayers - gamemodes/santosrp/gamemode/sh_pacmodels.lua:177
    3. unknown - gamemodes/santosrp/gamemode/cl_init.lua:113

**Comment by xbread** [comment]
Download pac3

**Comment by Bladadah** [comment]
https://gyazo.com/b4c99ea17d17cf1fa416655fa3633226

**Comment by Bladadah** [comment]
Also, could I get all the commands life how to whitelist ppl and stuff like that.

**Comment by xbread** [comment]
ill Push an update to remove those and give you commands in a few hours

**Comment by Bladadah** [comment]
Alright nice, thanks

**Comment by Bladadah** [comment]
ETA on the update?

**Comment by Bladadah** [comment]
I got the license_plates and it's not displaying it on the cars

**Comment by Bladadah** [comment]
??

**Comment by Bladadah** [comment]
Any updates yet?

**Comment by xbread** [comment]
Pushed an update for the scoreboard menu, but I am not seeing anything relating to drawing an Icon at (0,0)

**Comment by Bladadah** [comment]
Ah ok, you know how to fix the license plate system?

**Comment by xbread** [comment]
add me on discord Bread#0105

**Comment by xbread** [comment]
Problem seems to have been solved if you need help message me on discord or reopen this.

**Comment by matix2** [comment]
Hello, can you tell me what was the problem with this errors? https://pastebin.com/97mmR04z, im getting the same errors

nvm fixed.
