### ISSUE TITLE
Issues with data saving.

### ISSUE THREAD

**Issue by justyrusty** [xbread/Open-Source-Santos#14]
[ERROR] gamemodes/santosrp/gamemode/sv_mysql_player.lua:386: bad argument #1 to 'TableToJSON' (table expected, got string)
  1. TableToJSON - [C]:-1
   2. InsdupCharacterDataStoreVar - gamemodes/santosrp/gamemode/sv_mysql_player.lua:386
    3. unknown - gamemodes/santosrp/gamemode/sv_mysql_player.lua:544
     4. CommitPlayerDiffs - gamemodes/santosrp/gamemode/sv_mysql_player.lua:438
      5. PlayerDisconnected - gamemodes/santosrp/gamemode/sv_mysql.lua:46
       6. unknown - gamemodes/santosrp/gamemode/init.lua:149

This error shows up when disconnecting. Been looking into it for a while now, but no avail. Help would be appreciated.

**Comment by xbread** [comment]
What version of TMYSQL are you using?

**Comment by justyrusty** [comment]
Figured it out, thanks @xbread!
