### ISSUE TITLE
Skypaint errors

### ISSUE THREAD

**Issue by minesettimi** [xbread/Open-Source-Santos#3]
I keep getting spammed this error in the server console when I try to join it.
` [ERROR] gamemodes/base/entities/entities/env_skypaint.lua:110: attempt to call method 'SetSunNormal' (a nil value)
1. unknown - gamemodes/base/entities/entities/env_skypaint.lua:110`

**Comment by minesettimi** [comment]
That error is gone but now I get:
14:48:44: [ERROR] gamemodes/santosrp/gamemode/cl_init.lua:135: attempt to index field 'Gui' (a nil value)
14:48:44: 1. unknown - gamemodes/santosrp/gamemode/cl_init.lua:135

**Comment by xbread** [comment]
Not sure why theres an error with drawing the GUI. But the 'SetSunNorma' is a base gamemode error try reinstalling the base gamemode from the official facepunch site.

**Comment by minesettimi** [comment]
Whenever I join I get this 
![image](https://user-images.githubusercontent.com/35171319/47954133-114cd280-df5d-11e8-8909-71c506fe911d.png)

**Comment by minesettimi** [comment]
it seems that the gamemode isn't sending me the client code for everything to work.

**Comment by xbread** [comment]
Pretty weird what host are you using @minesettimi ? or are you hosting off your local machine

**Comment by minesettimi** [comment]
Krypton

**Comment by minesettimi** [comment]
Now I have this: 
20:8:59: [ERROR] gamemodes/santosrp/gamemode/init.lua:108: attempt to index field 'FireSystem' (a nil value)
20:8:59: 1. unknown - gamemodes/santosrp/gamemode/init.lua:108
20:8:59:
20:8:59:
20:8:59: [ERROR] gamemodes/santosrp/gamemode/init.lua:112: attempt to index field 'Inv' (a nil value)
20:8:59: 1. unknown - gamemodes/santosrp/gamemode/init.lua:112
20:8:59:
20:8:59:
20:8:59: [ERROR] gamemodes/santosrp/gamemode/init.lua:108: attempt to index field 'FireSystem' (a nil value)
20:8:59: 1. unknown - gamemodes/santosrp/gamemode/init.lua:108
20:8:59:
20:8:59:
20:8:59: [ERROR] gamemodes/santosrp/gamemode/init.lua:112: attempt to index field 'Inv' (a nil value)
20:8:59: 1. unknown - gamemodes/santosrp/gamemode/init.lua:112
20:8:59:
20:8:59:
20:8:59: [ERROR] gamemodes/santosrp/gamemode/init.lua:108: attempt to index field 'FireSystem' (a nil value)
20:8:59: 1. unknown - gamemodes/santosrp/gamemode/init.lua:108
20:8:59:
20:8:59:
20:8:59: [ERROR] gamemodes/santosrp/gamemode/init.lua:112: attempt to index field 'Inv' (a nil value)
20:8:59: 1. unknown - gamemodes/santosrp/gamemode/init.lua:112

**Comment by xbread** [comment]
Issue closed: I already told you what needed to be done this is most likely an SQL error
