### ISSUE TITLE
stuck on read only

### ISSUE THREAD

**Issue by julian12517** [xbread/Open-Source-Santos#9]
says its in read only mode and wont write santos files to the db

**Comment by xbread** [comment]
Can you make a video of you doing some things then relogging. I havent had this issue and I used this gamemode within the last month.

**Comment by julian12517** [comment]
`[SQL] Read-only database connected.
[SQL] Write worker 1 connected.
[SQL] Write worker 2 connected.
[SQL] Write worker 3 connected.
[SQL] Write worker 4 connected.
[SQL] Write worker 5 connected.
[SQL] Write worker 6 connected.
[SQL] Write worker 7 connected.
[SQL] Write worker 8 connected.
[SQL] Initializing gamemode tables...

[ERROR] gamemodes/santosrp/gamemode/sv_mysql.lua:268: attempt to call method 'IsConnected' (a nil value)
  1. PooledQueryWrite - gamemodes/santosrp/gamemode/sv_mysql.lua:268
   2. InitGamemodeTables - gamemodes/santosrp/gamemode/sv_mysql_player.lua:35
    3. Connect - gamemodes/santosrp/gamemode/sv_mysql.lua:29
     4. unknown - gamemodes/santosrp/gamemode/init.lua:50`
     
thats the first sql related thing that comes up in server log

**Comment by julian12517** [comment]
i honestly don't even know what the issue could possibly be i've been trying constantly to fix this issue over the past couple days and nothing

**Comment by xbread** [comment]
You are using TMYSQL4 correct also, have you checked if external connections are enabled on your database <- if not done by your host by default

Edit: ensure you're using this repo: https://github.com/bkacjios/gm_tmysql4 
In the future I might update the gamemode to use MYSQLOO just never see anyone really use this gamemode that much tho

**Comment by julian12517** [comment]
alright so using that got rid of the error but it still says read only

**Comment by julian12517** [comment]
nevermind it's working now thanks man

**Comment by julian12517** [comment]
would you happen to have a list of commands for whitelisting etc...

**Comment by xbread** [comment]
The command itself can be found in sv_jobs.lua also, add me on discord if you have any other questions bread#4487
A few commands:
srp_admin_whitelist_player <player name> jobid
srp_dev_give_money <amount>
srp_dev_remove // removes the ent you're looking at 
srp_dev_change_player_name <steamid> <newname>
